// Copyright 2024 Vincents AI
// SPDX-License-Identifier: MIT OR Apache-2.0

use super::types::*;
use anyhow::Result;
use async_trait::async_trait;
use std::sync::Arc;
use tokio::sync::RwLock;

/// Metrics exporter trait
#[async_trait]
pub trait MetricsExporter: Send + Sync {
    async fn export(&self) -> Result<String>;
    fn name(&self) -> &str;
}

/// Prometheus metrics exporter
pub struct PrometheusExporter {
    metrics: Arc<RwLock<Vec<Metric>>>,
}

impl PrometheusExporter {
    pub fn new() -> Self {
        Self {
            metrics: Arc::new(RwLock::new(Vec::new())),
        }
    }

    #[allow(dead_code)] // Public API — not yet called from production code
    pub fn with_metrics(metrics: Arc<RwLock<Vec<Metric>>>) -> Self {
        Self { metrics }
    }

    #[allow(dead_code)] // Internal method for batch metric updates
    async fn update_metrics(&self, metrics: Vec<Metric>) {
        let mut current = self.metrics.write().await;
        current.extend(metrics);
    }

    fn format_metric(&self, metric: &Metric) -> String {
        let labels_str = if metric.labels.is_empty() {
            String::new()
        } else {
            let labels: Vec<String> = metric
                .labels
                .iter()
                .map(|(k, v)| format!("{}=\"{}\"", k, v))
                .collect();
            format!("{{{}}}", labels.join(","))
        };

        let value = match &metric.value {
            MetricValue::Counter(v) => v.to_string(),
            MetricValue::Gauge(v) => v.to_string(),
            MetricValue::Histogram(v) => {
                format!(
                    "{{{}}}",
                    v.iter()
                        .map(|x| x.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                )
            }
            MetricValue::Summary {
                count,
                sum,
                min,
                max,
                ..
            } => {
                format!("count={}, sum={}, min={}, max={}", count, sum, min, max)
            }
        };

        match &metric.metric_type {
            MetricType::Counter => {
                format!(
                    "{}_total{} {} {}\n",
                    sanitize_metric_name(&metric.name),
                    labels_str,
                    value,
                    metric.timestamp.timestamp_millis()
                )
            }
            MetricType::Gauge => {
                format!(
                    "{}{} {} {}\n",
                    sanitize_metric_name(&metric.name),
                    labels_str,
                    value,
                    metric.timestamp.timestamp_millis()
                )
            }
            MetricType::Histogram => {
                format!(
                    "{}_bucket{} {} {}\n",
                    sanitize_metric_name(&metric.name),
                    labels_str,
                    value,
                    metric.timestamp.timestamp_millis()
                )
            }
            MetricType::Summary => {
                format!(
                    "{}{} {} {}\n",
                    sanitize_metric_name(&metric.name),
                    labels_str,
                    value,
                    metric.timestamp.timestamp_millis()
                )
            }
        }
    }
}

#[async_trait]
impl MetricsExporter for PrometheusExporter {
    async fn export(&self) -> Result<String> {
        let metrics = self.metrics.read().await;
        let mut output = String::new();

        output.push_str("# Skylet Plugin Metrics\n");
        output.push_str("# Generated by PrometheusExporter\n\n");

        for metric in metrics.iter() {
            output.push_str(&self.format_metric(metric));
        }

        Ok(output)
    }

    fn name(&self) -> &str {
        "prometheus"
    }
}

impl Default for PrometheusExporter {
    fn default() -> Self {
        Self::new()
    }
}

/// OpenTelemetry metrics exporter
pub struct OpenTelemetryExporter {
    metrics: Arc<RwLock<Vec<Metric>>>,
    #[allow(dead_code)] // Stored for future OTel HTTP export endpoint
    endpoint: String,
}

impl OpenTelemetryExporter {
    pub fn new(endpoint: String) -> Self {
        Self {
            metrics: Arc::new(RwLock::new(Vec::new())),
            endpoint,
        }
    }

    #[allow(dead_code)] // Public API — not yet called from production code
    pub fn with_metrics(metrics: Arc<RwLock<Vec<Metric>>>, endpoint: String) -> Self {
        Self { metrics, endpoint }
    }

    #[allow(dead_code)] // Internal method for batch metric updates
    async fn update_metrics(&self, metrics: Vec<Metric>) {
        let mut current = self.metrics.write().await;
        current.extend(metrics);
    }

    fn format_metric(&self, metric: &Metric) -> String {
        let labels: Vec<(String, String)> = metric
            .labels
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();

        let value = match &metric.value {
            MetricValue::Counter(v) => v.to_string(),
            MetricValue::Gauge(v) => v.to_string(),
            MetricValue::Histogram(v) => v
                .iter()
                .map(|x| x.to_string())
                .collect::<Vec<_>>()
                .join(","),
            MetricValue::Summary {
                count,
                sum,
                min,
                max,
                quantiles,
            } => {
                format!(
                    "count={}, sum={}, min={}, max={}, quantiles={}",
                    count,
                    sum,
                    min,
                    max,
                    quantiles
                        .iter()
                        .map(|(q, v)| format!("{}={}", q, v))
                        .collect::<Vec<_>>()
                        .join(",")
                )
            }
        };

        let metric_json = serde_json::json!({
            "name": sanitize_metric_name(&metric.name),
            "value": value,
            "timestamp": metric.timestamp.timestamp_millis(),
            "labels": labels,
            "type": format!("{:?}", metric.metric_type).to_lowercase()
        });

        serde_json::to_string(&metric_json).unwrap_or_else(|_| "{}".to_string())
    }
}

#[async_trait]
impl MetricsExporter for OpenTelemetryExporter {
    async fn export(&self) -> Result<String> {
        let metrics = self.metrics.read().await;
        let mut lines = Vec::new();

        for metric in metrics.iter() {
            lines.push(self.format_metric(metric));
        }

        Ok(lines.join("\n"))
    }

    fn name(&self) -> &str {
        "opentelemetry"
    }
}

/// Simple text metrics exporter for debugging
pub struct TextExporter {
    metrics: Arc<RwLock<Vec<Metric>>>,
}

impl TextExporter {
    pub fn new() -> Self {
        Self {
            metrics: Arc::new(RwLock::new(Vec::new())),
        }
    }

    #[allow(dead_code)] // Public API — not yet called from production code
    pub fn with_metrics(metrics: Arc<RwLock<Vec<Metric>>>) -> Self {
        Self { metrics }
    }

    #[allow(dead_code)] // Internal method for batch metric updates
    async fn update_metrics(&self, metrics: Vec<Metric>) {
        let mut current = self.metrics.write().await;
        current.extend(metrics);
    }
}

#[async_trait]
impl MetricsExporter for TextExporter {
    async fn export(&self) -> Result<String> {
        let metrics = self.metrics.read().await;
        let mut output = String::new();

        for metric in metrics.iter() {
            output.push_str(&format!(
                "{}[type={:?}, value={:?}] at {} with labels {:?}\n",
                metric.name,
                metric.metric_type,
                metric.value,
                metric.timestamp.format("%Y-%m-%d %H:%M:%S"),
                metric.labels
            ));
        }

        Ok(output)
    }

    fn name(&self) -> &str {
        "text"
    }
}

impl Default for TextExporter {
    fn default() -> Self {
        Self::new()
    }
}

/// Sanitize metric name for Prometheus
fn sanitize_metric_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    #[allow(unused_imports)]
    use std::collections::HashMap;

    #[tokio::test]
    async fn test_prometheus_exporter() {
        let exporter = PrometheusExporter::new();

        let metrics = vec![
            Metric::counter("test_counter".to_string(), 42)
                .with_label("plugin".to_string(), "test".to_string()),
            Metric::gauge("test_gauge".to_string(), 3.14),
        ];

        exporter.update_metrics(metrics).await;

        let output = exporter.export().await.unwrap();
        assert!(output.contains("test_counter_total"));
        assert!(output.contains("test_gauge"));
        assert!(output.contains("42"));
        assert!(output.contains("3.14"));
    }

    #[tokio::test]
    async fn test_opentelemetry_exporter() {
        let exporter = OpenTelemetryExporter::new("http://localhost:4318".to_string());

        let metrics = vec![Metric::counter("test_counter".to_string(), 1)];

        exporter.update_metrics(metrics).await;

        let output = exporter.export().await.unwrap();
        assert!(output.contains("test_counter"));
    }

    #[tokio::test]
    async fn test_text_exporter() {
        let exporter = TextExporter::new();

        let metrics = vec![Metric::counter("test".to_string(), 1)];

        exporter.update_metrics(metrics).await;

        let output = exporter.export().await.unwrap();
        assert!(output.contains("test"));
        assert!(output.contains("Counter"));
    }

    #[test]
    fn test_sanitize_metric_name() {
        assert_eq!(sanitize_metric_name("test_metric"), "test_metric");
        assert_eq!(sanitize_metric_name("test-metric"), "test_metric");
        assert_eq!(sanitize_metric_name("test.metric"), "test_metric");
        assert_eq!(sanitize_metric_name("test metric"), "test_metric");
    }

    #[test]
    fn test_prometheus_format() {
        let exporter = PrometheusExporter::new();

        let metric = Metric::counter("test_counter".to_string(), 42)
            .with_label("plugin".to_string(), "test_plugin".to_string());

        let formatted = exporter.format_metric(&metric);
        assert!(formatted.contains("test_counter_total"));
        assert!(formatted.contains("plugin=\"test_plugin\""));
        assert!(formatted.contains("42"));
    }
}
