apiVersion: v1
kind: Service
metadata:
  name: skylet
  namespace: skylet
  labels:
    app: skylet
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: skylet
---
apiVersion: v1
kind: Service
metadata:
  name: skylet-lb
  namespace: skylet
  labels:
    app: skylet
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: skylet
